[platformio]
src_dir = firmware/src
include_dir = firmware/include
data_dir = firmware/data

[env:esp32doit-devkit-v1]
platform = espressif32@6.12.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
extra_scripts = pre:firmware/scripts/sync_web.py

lib_deps =
  pololu/VL53L0X
  madhephaestus/ESP32Servo
  bblanchon/ArduinoJson
  miguelbalboa/MFRC522@^1.4.12
  jasonacox/TM1637TinyDisplay@^1.1.0

build_flags =
  -D CORE_DEBUG_LEVEL=1
